---
# These are sensible defaults which can be overriden in your own settings.yaml
# file.
#
# Note: You must still define the following keys:
#
#   * account-sync.id : UUID

host: "*"
hostname: "localhost"
port: 3000
base-url: ""

name: "QuickBooks for Communes"

db:
    host: ""
    username: ""
    password: ""
    name: "qb-for-communes"
    connection-count: 5

tls:
    enable: true
    allow-insecure: false
    key-file: "key.pem"
    cert-file: "cert.pem"
    cert-chain-files: []

account-sync:
    interval: 10
